services:

   openldap:
     image: osixia/openldap:latest
     environment:
       LDAP_DOMAIN: "example.org"
     command: --copy-service
     volumes:
      - ./docker-example/ldap-config:/container/service/slapd/assets/config/bootstrap/ldif/custom

   cas:
     image: ghcr.io/esupportail/apereo-cas-ldap:7.3.6
     volumes:
       - ./docker-example/cas-config:/etc/cas
     ports:
       - "8080:8080"
     depends_on:
       openldap:
         condition: service_started
