services:

   openldap:
     image: osixia/openldap:latest
     environment:
       LDAP_DOMAIN: "example.org"
     command: --copy-service
     ports:
       - "3980:389"
     volumes:
      - ./docker/ldap-config:/container/service/slapd/assets/config/bootstrap/ldif/custom

   cas:
     image: ghcr.io/esupportail/apereo-cas-ldap-mfa:7.2.7.1
     volumes:
       - ./docker/cas-config:/etc/cas
       - ./docker/cas-config/tmp-cas:/tmp/cas
     depends_on:
       openldap:
         condition: service_started
